AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - Gemfile
    - vendor/**/*
    - config/environments/*
    - bin/**/*
    - lib/**/*.rake
    - config/**
  SuggestExtensions: false

# METRICS
Metrics/MethodLength:
  Max: 300

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 90

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

# STYLE
Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Proc:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
