version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - 1234:1234
      - 26162:26162
    volumes:
      - .:/app
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:alpine3.16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - ${HOME}/docker/postgresql/db:/var/lib/postgresql/data:z
    ports:
      - "15432:5432"
